fix for AttributeError 'x' in numpy.ndarray
Fixes late game error that occurs because cell has no attribute 'x' or 'y', instead, index '0' and '1' are used.